### PR TITLE
Use the BackHandler to navigate to the previous page

### LINKED ISSUE #11: After updating the library to 1.4.0, it crashes after running the application
After updating the library to 1.4.0, it crashes after running the application

Log: 
<details>

``` java
java.lang.NoSuchMethodError: No interface method paneExpansionDraggable-d8LSEHM(Landroidx/compose/ui/Modifier;Landroidx/compose/material3/adaptive/layout/PaneExpansionState;FLandroidx/compose/foundation/interaction/MutableInteractionSource;)Landroidx/compose/ui/Modifier; in class Landroidx/compose/material3/adaptive/layout/ThreePaneScaffoldScope; or its super classes (declaration of 'androidx.compose.material3.adaptive.layout.ThreePaneScaffoldScope' appears in /data/app/~~7jfo48VaHsmzZXBuWPS-1A==/ro.cosminmihu.ktor.monitor.sample-OuhrKGWTOgzEfZs7KjseXg==/base.apk!classes3.dex)
 at ro.cosminmihu.ktor.monitor.ui.main.ComposableSingletons$MainContentKt$lambda-1$1.invoke(MainContent.kt:74)
 at ro.cosminmihu.ktor.monitor.ui.main.ComposableSingletons$MainContentKt$lambda-1$1.invoke(MainContent.kt:71)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:142)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt$ThreePaneScaffold$3$1$4.invoke(ThreePaneScaffold.kt:239)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt$ThreePaneScaffold$3$1$4.invoke(ThreePaneScaffold.kt:238)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
 at androidx.compose.material3.adaptive.layout.DefaultThreePaneScaffoldOverride$ThreePaneScaffold$contents$1.invoke(ThreePaneScaffold.kt:263)
 at androidx.compose.material3.adaptive.layout.DefaultThreePaneScaffoldOverride$ThreePaneScaffold$contents$1.invoke(ThreePaneScaffold.kt:263)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
 at androidx.compose.ui.layout.LayoutKt$combineAsVirtualLayouts$1.invoke(Layout.kt:435)
 at androidx.compose.ui.layout.LayoutKt$combineAsVirtualLayouts$1.invoke(Layout.kt:176)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
 at androidx.compose.material3.adaptive.layout.DefaultThreePaneScaffoldOverride.ThreePaneScaffold(ThreePaneScaffold.kt:992)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt$ThreePaneScaffold$3.invoke(ThreePaneScaffold.kt:244)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt$ThreePaneScaffold$3.invoke(ThreePaneScaffold.kt:197)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
 at androidx.compose.ui.layout.LookaheadScopeKt.LookaheadScope(LookaheadScope.kt:60)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt.ThreePaneScaffold(ThreePaneScaffold.kt:197)
 at androidx.compose.material3.adaptive.layout.ThreePaneScaffoldKt.ThreePaneScaffold(ThreePaneScaffold.kt:147)
 at androidx.compose.material3.adaptive.layout.ListDetailPaneScaffoldKt.ListDetailPaneScaffold(ListDetailPaneScaffold.kt:94)
 at ro.cosminmihu.ktor.monitor.ui.main.MainContentKt$MainContent$1.invoke(MainContent.kt:30)
 at ro.cosminmihu.ktor.monitor.ui.main.MainContentKt$MainContent$1.invoke(MainContent.kt:29)
```

<details>

### PR DESCRIPTION
**Pull request by keta1**
- Use the BackHandler to navigate to the previous page
- Bump `compose-multiplatform` to 1.8.0-alpha03 and `compose-adaptive` to 1.1.0-alpha03. (fixed #11)

### CODE REVIEW

**Review by CosminMihuMDC — APPROVED** [review]
Excellent catch 🙏
